Adding PAPI Placeholders about MissileWars
RedstoneFuture/missilewars pull request #45
Opened 2022-10-24 17:32 UTC by RedstoneFuture

2022-10-24 17:52 UTC, Butzlabben requested changes

2022-10-24 17:52 UTC, Butzlabben commented on missilewars-plugin/src/main/java/de/butzlabben/missilewars/MissileWars.java
> +        if(Bukkit.getPluginManager().getPlugin("PlaceholderAPI") != null) {
Formatting (space between if and brackets). Please always format files before commiting (Strg + Alt + L on IntelliJ)

```suggestion
        if (Bukkit.getPluginManager().getPlugin("PlaceholderAPI") != null) {
```

2022-10-24 17:52 UTC, Butzlabben commented on missilewars-plugin/src/main/java/de/butzlabben/missilewars/MissileWars.java
> +            new MissileWarsPlaceholder(this).register();
Maybe add Info Log Message that the placeholders were successfully registered.

2022-10-24 17:52 UTC, Butzlabben commented on missilewars-plugin/src/main/java/de/butzlabben/missilewars/util/MissileWarsPlaceholder.java
> +            if (!offlinePlayer.isOnline()) return "ERROR: No a player!";
Maybe change the message to something "player is not online"?

2022-10-24 17:52 UTC, Butzlabben commented on missilewars-plugin/src/main/java/de/butzlabben/missilewars/util/MissileWarsPlaceholder.java
> +            if (playerGame == null) return "ERROR: Wrong world!";
Make message more precise, as lobbies can be in a specific area in a world (they could be in a world with a lobby, but in the lobby)

2022-10-24 17:52 UTC, Butzlabben commented on missilewars-plugin/src/main/java/de/butzlabben/missilewars/util/MissileWarsPlaceholder.java
> +                }
The comments here are very good. Maybe you could add a new section in the README.md with a link to a new wiki page containing all possible placeholders.

2022-10-25 08:40 UTC, RedstoneFuture commented on missilewars-plugin/src/main/java/de/butzlabben/missilewars/util/MissileWarsPlaceholder.java
> +                }
I have referred to the documentation in the README. We don't need to be more precise about the placeholders, I think.

2022-10-25 08:42 UTC, Butzlabben approved these changes

2022-10-25 08:42 UTC, Butzlabben commented on missilewars-plugin/src/main/java/de/butzlabben/missilewars/util/MissileWarsPlaceholder.java
> +                if (params.equalsIgnoreCase("lobby_displayname_" + lobby.getName())) {
Good catch 👍

2022-10-25 08:43 UTC, merged