Improvement/better game scoreboard
RedstoneFuture/missilewars pull request #9
Opened 2022-02-13 11:38 UTC by RedstoneFuture

2022-03-07 22:23 UTC, daniel-naegele requested changes

2022-03-07 22:23 UTC, daniel-naegele commented on missilewars-plugin/src/main/java/de/butzlabben/missilewars/wrapper/game/Team.java
> +            // TODO remove scoreboard
Could you explain what you mean by this comment? And what is there still to do?

2022-03-07 22:23 UTC, daniel-naegele commented on missilewars-plugin/src/main/java/de/butzlabben/missilewars/Config.java
> +        List<String> scoreboardLines = cfg.getStringList("sidebar.entries");
Please inline this variable (`return cfg.getStringList("...");`)

2022-03-07 22:23 UTC, daniel-naegele commented on missilewars-plugin/src/main/java/de/butzlabben/missilewars/Config.java
Please stick to the java formatting and add lines inbetween methods

2022-03-07 22:23 UTC, daniel-naegele commented on missilewars-plugin/src/main/java/de/butzlabben/missilewars/listener/EndListener.java
> +        // TODO remove scoreboard
Same as in Team.java, why is TODO comment?

2022-03-07 22:23 UTC, daniel-naegele commented on missilewars-plugin/src/main/java/de/butzlabben/missilewars/util/ScoreboardManager.java
> +    private String scoreBoardTitle = Config.getScoreboardTitle();
Please make final what can be final

2022-03-07 22:23 UTC, daniel-naegele commented on missilewars-plugin/src/main/java/de/butzlabben/missilewars/util/ScoreboardManager.java
> +    private int maxScoreboardLines = 15;
Please declare constants as private, final and static and name it UPPERCASE. Also, why is this not used?

2022-03-07 22:23 UTC, daniel-naegele commented on missilewars-plugin/src/main/java/de/butzlabben/missilewars/util/ScoreboardManager.java
> +            // VersionUtil.setScoreboardTeamColor(t, ChatColor.getByChar(team2.getColorCode().charAt(1)));
Why did you comment out this line? Please add either an explanation or remove it entirely

2022-03-07 22:23 UTC, daniel-naegele commented on missilewars-plugin/src/main/java/de/butzlabben/missilewars/util/ScoreboardManager.java
> +            if (team1.getMembers().size() > memberListMaxSize) {
Please replace if/else with `team1ListSize = Math.min(team1.getMembers().size(), memberListMaxSize);`

2022-03-07 22:23 UTC, daniel-naegele commented on missilewars-plugin/src/main/java/de/butzlabben/missilewars/util/ScoreboardManager.java
> +            if (team2.getMembers().size() > memberListMaxSize) {
Same as above

2022-03-07 22:23 UTC, Butzlabben commented on missilewars-plugin/src/main/java/de/butzlabben/missilewars/util/ScoreboardManager.java
> +     * This method create a team for the scoreboard and add it to the teams ArrayList.
create -> creates, add -> adds

2022-03-07 22:23 UTC, Butzlabben commented on missilewars-plugin/src/main/java/de/butzlabben/missilewars/util/ScoreboardManager.java
> +     * and the using of the member-list placeholders for booth teams.
booth -> both

2022-03-07 22:23 UTC, Butzlabben commented on missilewars-plugin/src/main/java/de/butzlabben/missilewars/util/ScoreboardManager.java
> +        return (team1ListSize + team2ListSize);
(team1ListSize + team2ListSize) -> team1ListSize + team2ListSize

2022-03-07 22:23 UTC, Butzlabben commented on missilewars-plugin/src/main/java/de/butzlabben/missilewars/util/ScoreboardManager.java
> +        Not possible! When a user leaves the game, the scoreboard must be reset.
What is this code doing here?

2022-03-07 22:23 UTC, Butzlabben commented on missilewars-plugin/src/main/java/de/butzlabben/missilewars/util/ScoreboardManager.java
> +                int players = 0;
maybe rename variable to `currentPlayerIndex` or something

2022-03-07 22:25 UTC, RedstoneFuture commented on missilewars-plugin/src/main/java/de/butzlabben/missilewars/wrapper/game/Team.java
> +            // TODO remove scoreboard
It's a deprecated method.

2022-03-07 22:57 UTC, RedstoneFuture commented on missilewars-plugin/src/main/java/de/butzlabben/missilewars/listener/EndListener.java
> +        // TODO remove scoreboard
It's a deprecated method.

2022-03-07 23:06 UTC, RedstoneFuture commented on missilewars-plugin/src/main/java/de/butzlabben/missilewars/Config.java
![grafik](https://user-images.githubusercontent.com/4140635/157133238-f28561c4-3413-49bf-bc97-518bbc2a811f.png)
It is currently grouped by topic.

2022-03-12 02:47 UTC, Butzlabben requested changes

2022-03-12 02:47 UTC, Butzlabben commented on missilewars-plugin/src/main/java/de/butzlabben/missilewars/listener/EndListener.java
> +        p.setHealth(p.getAttribute(Attribute.GENERIC_MAX_HEALTH).getDefaultValue());
I think that this is not compatible with 1.8 and some of the higher versions. Please stick to `p.setHealth(p.getMaxHealth());`

2022-03-12 02:47 UTC, Butzlabben commented on missilewars-plugin/src/main/java/de/butzlabben/missilewars/listener/GameListener.java
> +            p.setHealth(p.getAttribute(Attribute.GENERIC_MAX_HEALTH).getDefaultValue());
Same as in EndListener

2022-03-12 02:47 UTC, Butzlabben commented on missilewars-plugin/src/main/java/de/butzlabben/missilewars/util/ScoreboardManager.java
> +     * and the using of the member-list placeholders for booths teams.
As in the old review: booth (booths) -> both

2022-03-12 02:48 UTC, Butzlabben commented on missilewars-plugin/src/main/java/de/butzlabben/missilewars/Config.java
The grouping is not the problem, but rather the formatting, just hit Strg + Alt + L once in this file (and overall in this project)

2022-03-12 02:51 UTC, Butzlabben commented on missilewars-plugin/src/main/java/de/butzlabben/missilewars/util/ScoreboardManager.java
> +     * This method register the scoreboard.
register -> registers (He, she, it, dass "S" muss mit)

2022-03-13 11:43 UTC, Butzlabben approved these changes

2022-03-13 11:43 UTC, merged